### ISSUE TITLE
`Module 101|ne:1023 not found.` potentially erroring on | character in step parameters

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1040]
In working on this: https://github.com/publiclab/image-sequencer-app/issues/6#issuecomment-485018092

I got this error about not being able to parse parameters for the `webgl-distort` module: 

`Module 101|ne:1023 not found.`

Full error here:

```
Module 101|ne:1023 not found.
TypeError: Cannot read property 'description' of undefined 
at insertStep (/srv/node_modules/image-sequencer/src/InsertStep.js:23:50) 
at InsertStep (/srv/node_modules/image-sequencer/src/InsertStep.js:61:3) at AddStep (/srv/node_modules/image-sequencer/src/AddStep.js:3:33) 
at Object.addSteps (/srv/node_modules/image-sequencer/src/ImageSequencer.js:75:29) 
at eachStep (/srv/node_modules/image-sequencer/src/Strings.js:132:17) 
at Array.forEach (<anonymous>) 
at Object.importString (/srv/node_modules/image-sequencer/src/Strings.js:131:21) 
at Object.sequencerInstance.loadImages (/srv/index.js:64:27) 
at /srv/node_modules/image-sequencer/src/ImageSequencer.js:179:23 
at /srv/node_modules/image-sequencer/src/ui/LoadImage.js:67:7
```

**Comment by Divy123** [comment]
@jywarren can you please provide some description here.

**Comment by VibhorCodecianGupta** [comment]
It's related to #1033 , working on it. will update as soon as i find a fix

**Comment by jywarren** [comment]
Indeed it's related, im actually not sure exactly what's happening, but I
would guess maybe it's splitting on the wrong character in the parameters
for webgl-distort?

**Comment by tech4GT** [comment]
Looking into this now!

**Comment by tech4GT** [comment]
@VibhorCodecianGupta Anything you would like to add here?

**Comment by tech4GT** [comment]
@jywarren I am seeing this error, do you think this can be linked?
<img width="664" alt="Screen Shot 2019-05-08 at 9 48 47 PM" src="https://user-images.githubusercontent.com/25617855/57390975-21c75980-71db-11e9-882d-b784860740d0.png">

**Comment by tech4GT** [comment]
Looks like I found one of the issues @publiclab/is-reviewers 
The name of fisheye-gl module is being used as "fisheye gl" which is why adding fisheye gl causes an error!

**Comment by HarshKhandeparkar** [comment]
The website doesn't even work. Try the latest example website locally. It
doesn't work. Adding modules throws an error.

**Comment by tech4GT** [comment]
Okay this is not specific to fisheye gl
<img width="664" alt="Screen Shot 2019-05-08 at 10 05 33 PM" src="https://user-images.githubusercontent.com/25617855/57392055-6e139900-71dd-11e9-8128-3c3a83a681e7.png">
cc @jywarren

**Comment by tech4GT** [comment]
Yeah I am trying to isolate the error!

**Comment by tech4GT** [comment]
@HarshKhandeparkar I think we might have to roll back a few commits here the problem appears to be deep rooted.

**Comment by tech4GT** [comment]
I'll try to figure out which commit added this code.

**Comment by HarshKhandeparkar** [comment]
I think @teisenhower had tried to rearrange the module names. That is maybe when the error started?

**Comment by HarshKhandeparkar** [comment]
I think @teisenhower had tried to rearrange the module names. That is maybe when the error started?

**Comment by HarshKhandeparkar** [comment]
This only happens in the demo though. CLI works. This is a BIG issue. Also urlHash works, so it is only the selector that is broken.

**Comment by tech4GT** [comment]
Okay, a lot of code has been pushed in since then I think. I'll open a new issue for this then.

**Comment by HarshKhandeparkar** [comment]
:+1:Ok

**Comment by tech4GT** [comment]
Harsh do you have any insight on the parsing error here?

**Comment by tech4GT** [comment]
I am trying to replicate it locally.

**Comment by HarshKhandeparkar** [comment]
We really need to refactor our UI code. It is extremely messy and
unreadable. Is there any SoC proposal which mentions such a thing?

**Comment by tech4GT** [comment]
I'm not really involved with soc so I'm not sure, sorry.

**Comment by HarshKhandeparkar** [comment]
Np

**Comment by jywarren** [comment]
Hi folks, this issue is quite long now so there are plenty of questions or topics that may need to be broken out into their own so we can follow up with them. I'll focus on the debugging of the parsing error with `|` characters.

> message port closed

I don't think that's it, but it could be - do you think the pipe character is in some way being read as a Linux pipe? But the error is not showing breaking on the pipe, it's breaking on either a `.` or a `:`, it looks like. 

Harsh - https://sequencer.publiclab.org/examples/#steps=contrast{} is working fine right now. Please open a new issue if you see an unrelated bug, thanks!

`fisheye gl` - that sounds bad, and would love a PR for this, and improved UI tests should catch something like this. But in the demo right now, it does seem to work for me: https://sequencer.publiclab.org/examples/#steps=contrast{},fisheye-gl{x:1|y:1}

You can see who touched files in the examples folder here: https://github.com/publiclab/image-sequencer/commits/main/examples

**Comment by jywarren** [comment]
Noting that we published to gh-pages on April 9th, but the commit by `teisenhower` you're mentioning was April 7th. So it seems unlikely or these errors would be appearing on the online demo right now.

**Comment by teisenhower** [comment]
Hey all 

Sorry I'm just now seeing this.

Not sure if this will help or not but when I worked on that previous dropdown issue I didn't rearrange things to alphabetical order. 

Please let me know if there is anything I can do to help with this. 

Thanks!

**Comment by jywarren** [comment]
Thanks Terrence! Sorry, I think it is unrelated to your code, so no
worries! We're just tracking a tough bug and working through all the
possibilities. Thanks so much!

**Comment by HarshKhandeparkar** [comment]
Sorry @teisenhower.

**Comment by teisenhower** [comment]
@jywarren No problem!

@HarshKhandeparkar No worries! Just wanted to make sure I could help if possible. Thanks!

**Comment by jywarren** [comment]
Hi @harshkhandeparkar, I agree with refactoring UI code, but a) let's address in a separate issue, and b) expanded UI tests would be a great first step before potentially breaking UI functionality, what do you think?

**Comment by jywarren** [comment]
https://codecov.io/gh/publiclab/image-sequencer/tree/main/examples/lib
