### ISSUE TITLE
issue installing gl package on arm

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1075]
I use Ubuntu on an ARM Chromebook and got this error on trying to run `npm install` (to release a new version):

```

> gl@4.2.2 install /home/warren/sites/image-sequencer/node_modules/gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=arm libc= platform=linux)
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/warren/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.18.0-19095-g86596f58eadf
gyp ERR! command "/home/warren/.nvm/versions/node/v8.11.1/bin/node" "/home/warren/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/warren/sites/image-sequencer/node_modules/gl
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package eslint is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gl@4.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/warren/.npm/_logs/2019-05-23T18_46_37_118Z-debug.log
```

Any advice? I'm looking at https://www.npmjs.com/package/gl

**Comment by jywarren** [comment]
Hmm people have been able to on a Raspberry Pi, which is also ARM: https://github.com/stackgl/headless-gl/issues/22

**Comment by jywarren** [comment]
Oooh https://github.com/yarnpkg/yarn/issues/1987

**Comment by jywarren** [comment]
Aha - https://github.com/stackgl/headless-gl#ubuntudebian

we should include this in our docs, for those running non-standard systems... it's required to build the `gl` module!

**Comment by HarshKhandeparkar** [comment]
@jywarren `sudo apt install libxi-dev` will fix this.

**Comment by jywarren** [comment]
Yes! I found in the headless-gl docs:

`sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config`

Closing, and will add to a README file. Thanks!

**Comment by HarshKhandeparkar** [comment]
It is run in our travis file. Also other things are installed. See the `.travis.yml`

**Comment by HarshKhandeparkar** [comment]
@jywarren it is not just for ARM, this can occur for any device. Mostly, fully operational OSes for desktop like Ubuntu and Linux mint will not have any probs as they have graphics drivers but devices without a GPU out of the box can have problems.
