### ISSUE TITLE
Test failures not appearing in Travis results

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1113]
Possibly related to #659, I'm seeing some test errors that are nonetheless reporting success in Travis. This is really concerning and I'd like to ensure that:

* [ ] we can first change settings so that these actually trigger a failure that's visible in Travis
* [ ] second, that we fix these bugs

@publiclab/is-reviewers is anyone available to take a look at these? @aashna27 or @Divy123 perhaps? Thank you!

https://travis-ci.org/publiclab/image-sequencer/jobs/545906882#L1061-L1091

```
/home/travis/build/publiclab/image-sequencer/node_modules/fisheyegl/src/fisheyegl.js:304
  window.FisheyeGl = FisheyeGl;
  ^
ReferenceError: window is not defined
    at Object.<anonymous> (/home/travis/build/publiclab/image-sequencer/node_modules/fisheyegl/src/fisheyegl.js:304:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Array.DoNothing (/home/travis/build/publiclab/image-sequencer/src/modules/FisheyeGl/Module.js:9:217)
    at insertStep (/home/travis/build/publiclab/image-sequencer/src/InsertStep.js:9:3390)
    at InsertStep (/home/travis/build/publiclab/image-sequencer/src/InsertStep.js:9:3604)
    at AddStep (/home/travis/build/publiclab/image-sequencer/src/AddStep.js:9:143)
    at Object.addSteps (/home/travis/build/publiclab/image-sequencer/src/ImageSequencer.js:9:4687)
    at Test.t (/home/travis/build/publiclab/image-sequencer/test/core/templates/module-test.js:23:15)
    at Test.bound [as _cb] (/home/travis/build/publiclab/image-sequencer/node_modules/tape/lib/test.js:77:32)
```

And: https://travis-ci.org/publiclab/image-sequencer/jobs/545906882#L910-L927

```

    ✖ colorbar module works correctly
    ----------------------------------
      operator: equal
      expected: true
      actual:   false
      at: <anonymous> (/home/travis/build/publiclab/image-sequencer/test/core/templates/module-test.js:50:11)
      stack: |-
  Error: colorbar module works correctly
  at Test.assert [as _assert] (/home/travis/build/publiclab/image-sequencer/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/travis/build/publiclab/image-sequencer/node_modules/tape/lib/test.js:77:32)
  at Test.equal (/home/travis/build/publiclab/image-sequencer/node_modules/tape/lib/test.js:386:10)
  at Test.bound [as equal] (/home/travis/build/publiclab/image-sequencer/node_modules/tape/lib/test.js:77:32)
  at /home/travis/build/publiclab/image-sequencer/test/core/templates/module-test.js:50:11
  at getDiffPixelsCoords (/home/travis/build/publiclab/image-sequencer/node_modules/looks-same/index.js:168:13)
  at Immediate.setImmediate (/home/travis/build/publiclab/image-sequencer/node_modules/looks-same/lib/utils.js:89:17)
  at runCallback (timers.js:810:20)
  at tryOnImmediate (timers.js:768:5)
  at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by Divy123** [comment]
https://github.com/publiclab/image-sequencer/issues/1127

**Comment by Divy123** [comment]
https://github.com/publiclab/image-sequencer/issues/1127

**Comment by jywarren** [comment]
Linking to #1550 and https://github.com/publiclab/image-sequencer/issues/659 !

**Comment by jywarren** [comment]
I believe this is now complete, but noting the connection to https://github.com/publiclab/image-sequencer/issues/1694

**Comment by jywarren** [comment]
Also noting #1684 !
