### ISSUE TITLE
ES6 failure in tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1245]
https://travis-ci.org/publiclab/image-sequencer/jobs/579551472 is showing an ES6 failure to recognize the `=>` syntax, although that doesn't seem to be what's failing. So, two issues: first that we should either change that syntax or be sure it works in tests, and second, we should make sure tests fail when an error like this pops up!

```
Transformation error; return original code
{ Error: Line 67: Unexpected token =>
    at constructError (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at expect (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2523:13)
    at parseGroupExpression (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:3200:9)
    at inheritCoverGrammar (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
    at parsePrimaryExpression (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:3239:20)
    at inheritCoverGrammar (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/home/travis/build/publiclab/image-sequencer/node_modules/istanbul/node_modules/esprima/esprima.js:3414:20)
  lineNumber: 67,
  description: 'Unexpected token =>',
  index: 2037 }
    Failed to parse file: /home/travis/build/publiclab/image-sequencer/src/modules/MinifyImage/Module.js
```

**Comment by jywarren** [comment]
It's in this file, btw!     Failed to parse file: /home/travis/build/publiclab/image-sequencer/src/modules/MinifyImage/Module.js

**Comment by jywarren** [comment]
Hi @Divy123 what do you think of this? Thanks!

**Comment by vaibhavmatta** [comment]
Hey @jywarren , Sorry, I was bit busy due to my university exams. I am back to the field now. May I try to figure out the solution for this issue? Thanks

**Comment by HarshKhandeparkar** [comment]
Yes sure.

**Comment by HarshKhandeparkar** [comment]
BTW, @jywarren we have babelify as a dependency. We can use it to babelify the tests before running them. I had run into a similar issue some time back so I had added babelify but I think I somehow circumvented the issue but forgot to remove the dep. It may be helpful now.

**Comment by keshav234156** [comment]
@jywarren  @HarshKhandeparkar the problem is with the istanbul version in package.json changing"istanbul": "^0.4.5" to  "istanbul": "^1.0.0-alpha.2" works.Had tried it locally.Should i open a PR which fixes this issue??

**Comment by vaibhavmatta** [comment]
@jywarren @HarshKhandeparkar Is the issue solved now?

**Comment by HarshKhandeparkar** [comment]
I think so. There is an open PR. You can review the PR if you want.

**Comment by vaibhavmatta** [comment]
Alright.! Thanks

**Comment by blurry-x-face** [comment]
I want to work on this issue!

**Comment by Divy123** [comment]
Assigned to @blurry-x-face .

**Comment by Divy123** [comment]
I guess this is solved. you may look into another issue.
Thanks for your issue.
