### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by MrAsimZahid** [publiclab/image-sequencer#1537]
![npm start error](https://user-images.githubusercontent.com/23510373/72665535-fca60e80-3a2a-11ea-884e-d65f9ed8a20b.png)
### Please describe the problem (or idea)
Receiving this error after running ```npm start ``` command
```

> image-sequencer@3.5.1 start /home/asim/image-sequencer
> grunt serve

Running "browserify:core" (browserify) task
>> Error: Parsing file /home/asim/image-sequencer/node_modules/fast-glob/out/readers/stream.js: Unexpected token (16:10)
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! image-sequencer@3.5.1 start: `grunt serve`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2020-01-18T14_42_07_091Z-debug.log
```
> What happened just before the problem occurred? Or what problem could this idea solve?
Entered ```npm start``` command
also tried ```sudo npm started```

> What did you expect to see that you didn't?
npm started

### Please show us where to look
README.md
https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system
Ubuntu 18.04 LTS
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Could you please tell us the `npm` and `nodejs` versions you are using?

**Comment by MrAsimZahid** [comment]
npm version = 6.13.6
Node version = v8.10.0

**Comment by HarshKhandeparkar** [comment]
Try running `npm rebuild --build-from-source`

**Comment by MrAsimZahid** [comment]
Received this error
```
> gl@4.4.0 install /home/asim/image-sequencer/node_modules/gl
> prebuild-install || node-gyp rebuild

Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/asim/image-sequencer/node_modules/gl
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.4.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gl@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2020-01-20T14_15_51_027Z-debug.log
```

**Comment by HarshKhandeparkar** [comment]
Please run the following commands
`sudo apt-get install -y build-essential xserver-xorg-dev libxext-dev libxi-dev libglu1-mesa-dev libglew-dev pkg-config`

**Comment by MrAsimZahid** [comment]
This command was successful.
```
sudo apt-get install -y build-essential xserver-xorg-dev libxext-dev libxi-dev libglu1-mesa-dev libglew-dev pkg-config
```
After I ran 
```
npm start
```
and received this error

```
> image-sequencer@3.5.1 start /home/asim/image-sequencer
> grunt serve

Running "browserify:core" (browserify) task
>> Error: Parsing file /home/asim/image-sequencer/node_modules/fast-glob/out/readers/sync.js: Unexpected token (15:10)
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! image-sequencer@3.5.1 start: `grunt serve`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2020-01-20T14_48_56_317Z-debug.log
```

**Comment by HarshKhandeparkar** [comment]
After running the first (`apt`) command I told you, try running `npm run setup` and then `npm start`.

**Comment by MrAsimZahid** [comment]
ran the 
```
sudo npm run setup
```
received this error
```
ERROR: Failed to download Chromium r674921! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/home/asim/image-sequencer/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/home/asim/image-sequencer/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/home/asim/image-sequencer/node_modules/puppeteer/install.js:64:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/asim/image-sequencer/node_modules/puppeteer/.local-chromium' }
npm WARN The package eslint is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.19.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2020-01-20T15_13_15_042Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! image-sequencer@3.5.1 setup: `npm i && npm i -g grunt grunt-cli && grunt build $$ npm rebuild --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2020-01-20T15_13_15_121Z-debug.log
```

**Comment by HarshKhandeparkar** [comment]
I have never seen that error before. Try googling it. This might help: https://github.com/albinekb/favicon-emoji/issues/13

**Comment by MrAsimZahid** [comment]
Resolved issue using this command
```
sudo npm install -g puppeteer --unsafe-perm=true --allow-root
```
Writing summary of whole issue and closing.
Thank you @HarshKhandeparkar

**Comment by MrAsimZahid** [comment]
Whole summary of issue.

First command
```
sudo apt-get install -y build-essential xserver-xorg-dev libxext-dev libxi-dev libglu1-mesa-dev libglew-dev pkg-config
```
then
```
sudo npm install -g puppeteer --unsafe-perm=true --allow-root
```
then 
```
npm start
```
Result should be a window open in the browser.

**Comment by HarshKhandeparkar** [comment]
Awesome!
