### ISSUE TITLE
Enable Asynchronous Processing

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#829]
### Asynchronous
The Image Sequencer processes can be run on an alternate thread using webworkers. Native support for workers has also been added to Node.js

### Use Case
Doing this will not slow down the browser as much as it did before. All other browser activities will work and sequencer will run on an alternate thread and only a spinner will be shown.

### Ideas
Do you have any other ideas? Any other ways to tackle this? Anything? Please let us know in the discussion(comments).

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi Harsh! Could you link back to the original issue and copy in some of the
links to libraries and docs that could help? I think there was a library
called Greenlet or something. Thanks!

**Comment by jywarren** [comment]
Oh sorry I read from my email, didn't see it was done!

**Comment by jywarren** [comment]
And https://github.com/publiclab/image-sequencer/issues/159

**Comment by Divy123** [comment]
I am new to web workers but I would love to work upon this.
@HarshKhandeparkar @jywarren waant your guidance here.
Please help me with this.
Since this is a performance issue, I want to work on it at a top priority.

**Comment by HarshKhandeparkar** [comment]
Since nodejs has workers support, can you girst try running different parts of sequencer on different threads? You will have to do some research on workers though.

**Comment by Divy123** [comment]
For sure!
Thanks a lot.

**Comment by Divy123** [comment]
@jywarren following #159, do you suggest to have run() on another thread ?
Also what are some other parameters you suggest keeping in mind?
Thanks!!
PS: Know that you are very busy but actually I am drafting my soc proposal for that I am exploring web workers and related concepts.

**Comment by Divy123** [comment]
> Greenlet is most effective when the work being done has relatively small inputs/outputs.
Also I found this on greenlet docs.
Will that be fruitful using @jywarren ?

**Comment by jywarren** [comment]
I think we basically need to try it and see, unfortunately. I guess this is
a vote in favor of doing the whole `run()` rather than passing back and
forth to/from the worker thread... what do you think?

**Comment by Divy123** [comment]
Yes I think that has to be the soution in that case.
Yes but one thing to keep in consideration is we cannot manipulate DOM from worker thread so some utility has to be provided to worker or returned by it to do the task outside worker thread.

**Comment by jywarren** [comment]
ah, indeed. So is it possible to use some kind of callback with the image
from each step?

**Comment by Divy123** [comment]
Will get to you back after exploring a bit more on this as I think the problem is since the data is copied not shared, returning images(heavy data)  has to be optimized.

**Comment by Divy123** [comment]
![Screenshot from 2019-03-31 16-43-21](https://user-images.githubusercontent.com/31225007/55288368-2fb3de80-53d4-11e9-9e92-299a546cc94f.png)

Since greenlet does not work with nodejs, I went through node-webworker.
But the issue I am facing is: 

```
internal/bootstrap/loaders.js:81
        mod = bindingObj[module] = getBinding(module);
                                   ^

Error: No such module: net
at process.binding (internal/bootstrap/loaders.js:81:36)
    at Object.<anonymous> (/home/divy/Desktop/practice/node_modules/webworker/lib/webworker.js:35:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/divy/Desktop/practice/main.js:1:76)
```
So I think we can make this happen only on browsers until we don't find a good solution for node.
@jywarren what do you think upon this?

**Comment by Divy123** [comment]
Also I am exploring the following for node:
https://www.npmjs.com/package/webworker-threads

**Comment by HarshKhandeparkar** [comment]
@Divy123 are you using a separate package? Doesn't nodejs have inbuilt support for workers? I think it should have because some node libs use promises, don't they? Also I think Varun had said that node has support for workers in a comment in the old issue.

Yes, he did here https://github.com/publiclab/image-sequencer/issues/159#issuecomment-395843135

cc @jywarren @tech4GT

**Comment by HarshKhandeparkar** [comment]
News!

Nodejs v11.7.0 has worker threads inbuilt.

https://codeforgeek.com/2019/01/getting-started-node-worker-thread/

**Comment by HarshKhandeparkar** [comment]
v10.5.0 has initial implementation of threads and v11.7.0 has full worker threads support.

**Comment by Divy123** [comment]
@HarshKhandeparkar latest version of node is 10.15.0 
So we shoud proceed that way.
We can use the native support in node v11.7.0 once it becomes the LTS but till then, I think we can proceed that way.

**Comment by Divy123** [comment]
@jywarren request a little help here.
Can you please help me out with how can I pass functions to workers since they are not allowed as per structured clone algorithm which web workers employ to copy data?

**Comment by HarshKhandeparkar** [comment]
> So we shoud proceed that way.
We can use the native support in node v11.7.0 once it becomes the LTS but till then, I think we can proceed that way.

This version won't be an LTS, node v12 will be. But anyways, :+1:

**Comment by HarshKhandeparkar** [comment]
> request a little help here.
Can you please help me out with how can I pass functions to workers since they are not allowed as per structured clone algorithm which web workers employ to copy data?

Can you drop a link to the docs/README of the package you are using?

**Comment by Divy123** [comment]
@HarshKhandeparkar may have a look
https://www.npmjs.com/package/webworker-threads

**Comment by HarshKhandeparkar** [comment]
Can you please explain a bit more? What is structured clone algorithm?

**Comment by HarshKhandeparkar** [comment]
What function do you want to pass into the worker?

**Comment by Divy123** [comment]
Structured clone algo is the one used to copy data from ine worker to another and it has certain restrictions.
Can have a look here:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

**Comment by Divy123** [comment]
Also I have to pass certain number of functions including the one that are imported through require() as require cannot be used inside worker threads.
So there is a lot to pass.
For example, I want to have run() on a worker thread and for that I have to certain functions like callback() to it.
Do you have any suggestions @HarshKhandeparkar @jywarren ?

**Comment by HarshKhandeparkar** [comment]
1. MDN docs document browser workers, node may be different.
2. You can create workers inside the run func, pass static data through postMessage and let the worker return the final pixels, again using postMessage.
3. You don't have to use require inside the workers, you can require outside and provide it to the worker.
4. This is from the docs,
> ortScripts( file [, file...] )
importScripts('a.js', 'b.js') loads one or more files from the disk and eval() them in the worker's instance scope.

Whatever I have said may not work. You will have to experiment. Correct me if I have said anything wrong. Please feel free to ask other queries(if any).

**Comment by HarshKhandeparkar** [comment]
Try this,
```js
var Worker = require('webworker-threads').Worker;
// var w = new Worker('worker.js'); // Standard API
 
// You may also pass in a function:
var worker = new Worker(function(){
  postMessage("I'm working before postMessage(function(var){return 2*var}).");
  this.onmessage = function(event) {
    postMessage(event.data(4)); // 8 (should be)
    self.close();
  };
});
worker.onmessage = function(event) {
  console.log("Worker said : " + event.data);
};
worker.postMessage(function(var){return 2*var});
```

**Comment by Divy123** [comment]
Actually the` importScripts()` runs the script most probably inside the file provided to it so the functions provided inside it will not work and moreover we cannot pass any args to it.
I will think about restructuring somethings here.
Thanks a lot @HarshKhandeparkar

**Comment by Divy123** [comment]
Looking at the code ..

**Comment by Divy123** [comment]
Also @HarshKhandeparkar can you please provide a link to the above code?

**Comment by Divy123** [comment]
Also the code provided is not running, it get stuck after logging 
```
worker said : I'm working before postMessage(function(var){return 2*var})

```
to the console.

**Comment by Divy123** [comment]
@jywarren request for your help here!!

**Comment by Divy123** [comment]
Also @tech4GT can you please help me with this.
I am including this in my SoC proposal, so I don't have much time left.

**Comment by Divy123** [comment]
I think we can break various parts of run function and have them on alternate threads.
What do you say on this?

**Comment by HarshKhandeparkar** [comment]
> Also the code provided is not running, it get stuck after logging

> ```worker said : I'm working before postMessage(function(var){return 2*var})
```
> to the console.

Thia should have logged `Worker Said : 8`

Ok, let's try something simpler.
```js
var Worker = require('webworker-threads').Worker;
// var w = new Worker('worker.js'); // Standard API
 
// You may also pass in a function:
var worker = new Worker(function(){
  postMessage("I'm working before postMessage(function(var){return 2*var}).");
  this.onmessage = function(event) {
    postMessage(event.data()); // 2 (should be)
    self.close();
  };
});
worker.onmessage = function(event) {
  console.log("Worker said : " + event.data); // Worker Said : 2
};
worker.postMessage(function(var){return 2});
```

I didn't find this code anywhere, I just edited the example code.

**Comment by HarshKhandeparkar** [comment]
You can try something even simpler, (I'm just trying to pass a function into the worker using postMessage).

```js
var Worker = require('webworker-threads').Worker;
// var w = new Worker('worker.js'); // Standard API
 
// You may also pass in a function:
var worker = new Worker(function(){
  postMessage("I'm working before postMessage");
  this.onmessage = function(event) {
    postMessage(typeof event.data); // function (should be)
    self.close();
  };
});
worker.onmessage = function(event) {
  console.log("Worker said : " + event.data); // Worker Said : function
};
worker.postMessage(function(var){console.log('hi')});
```

**Comment by Divy123** [comment]
@HarshKhandeparkar 
this is something that supports both browser and node .
https://www.npmjs.com/package/threads

**Comment by Divy123** [comment]
I think this is one of the most reliable library, has 11032 weakly downloads .

**Comment by niravasher** [comment]
This is what I have understood till now regarding web workers
![IMG_20190402_102541](https://user-images.githubusercontent.com/32176296/55377970-dc0cd680-5534-11e9-825e-ccd2f01866f7.jpg)

This is the way I am applying web workers to the DrawRectangle Module
![IMG_20190402_104441](https://user-images.githubusercontent.com/32176296/55378087-3017bb00-5535-11e9-862f-165d159c7b1b.jpg)
workers.onMessage() is outside extraManipulation() and inside workers.postMessage, I am returning output, changePixel, extraManippulation, format, image and callback. This might not be entirely right but I am having a fair idea about workers, require some help here. @jywarren @HarshKhandeparkar @Divy123

**Comment by Divy123** [comment]
@niravasher I am already working upon it.

**Comment by Divy123** [comment]
Also we first focus on Run.js file which is so much used.
